[reliability]
pilot_species = 3 # per coder per round
# i hyphotesize of why 3 because it is the minimum repetition to find mean?
coders = 3

significance_level = 0.10

[thresholds]

# the following three values are choosen based on the nearly Fibonacci sequence

initial_filter_pct = 50
coverage_pct = 35
variant_pct = 20

variant_min_species = 3
